apiVersion: v1
kind: Namespace
metadata:
  name: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
  namespace: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: acraksworkshop.azurecr.io/oapi:7999
        name: api
        imagePullPolicy: Always
        ports:
        - containerPort: 7999
        resources:
          requests:
            memory: "16Mi"
            cpu: "250m"
          limits:
            memory: "64Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
    name: api
    namespace: api
    labels:
        app: api
spec:
    type: ClusterIP
    ports:
    - port: 80
      targetPort: 7999
      protocol: TCP
      name: http
    selector:
        app: api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: api
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /weatherforecast
        pathType: Exact
        backend:
          service:
            name: api
            port:
              number: 80
