apiVersion: v1
kind: Namespace
metadata:
  name: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
  namespace: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: acraksworkshop.azurecr.io/oapi:7999
        name: api
        imagePullPolicy: Always
        ports:
        - containerPort: 7999
        resources:
          requests:
            memory: "5Mi"
            cpu: "50m"
          limits:
            memory: "50Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
    name: api
    namespace: api
    labels:
        app: api
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 7999
      protocol: TCP
      name: http
    selector:
        app: api
