apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
  namespace: api
spec:
  replicas: 10
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: acraksworkshop.azurecr.io/oapi:7999
        name: api
        imagePullPolicy: Always
        ports:
        - containerPort: 7999
        resources:
          requests:
            memory: "16Mi"
            cpu: "250m"
          limits:
            memory: "64Mi"
            cpu: "500m"
