name: 0 Testing

on:  workflow_dispatch

env:
  image_name: oapi
  tag: latest
  CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
  RESOURCE_GROUP: ${{ secrets.AZURE_RG }} 
  acr_name: ${{ secrets.ACR_NAME }} 
  

jobs:
  deploy-microservice:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          
          az aks get-credentials --name ${{ env.CLUSTER_NAME }} --resource-group ${{ env.RESOURCE_GROUP }}
          az aks command invoke --name ${{ env.CLUSTER_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --command "kubectl crete ns api"
         # az aks command invoke --name ${{ env.CLUSTER_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --command "kubectl create deploy api --image=${{ env.acr_name }}.azurecr.io/${{ env.image_name }}:${{ env.tag }} -n api"
          
          
         # kubectl crete ns api
         # kubectl create deploy api --image=${{ secrets.ACR }}.azurecr.io/${{ env.image_name }}:${{ env.tag }} -n api
         # kubectl autoscale deployment api --cpu-percent=30 --min=4 --max=100 -n api
          
          
      
