on: workflow_dispatch
name: Deploy AKS with OSM
jobs:
  deploy-cluster:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@main

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_SUPER_SP }}
    
    - name: Deploy AKS with OSM
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az aks create -n ${{ secrets.CLUSTER_NAME }} -g ${{ secrets.AZURE_RG }} --enable-addons open-service-mesh --attach-acr ${{ secrets.ACR_NAME }} --yes
          az aks nodepool update --enable-cluster-autoscaler --min-count 3 --max-count 10 -g ${{ secrets.AZURE_RG }} -n nodepool1 --cluster-name ${{ secrets.CLUSTER_NAME }}
