on: workflow_dispatch
name: 1 Deploy AKS with Ingress Controller
jobs:
  deploy-cluster:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@main

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_SUPER_SP }}
    
    - name: Deploy AKS with Ingress Controller
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az aks create -n ${{ secrets.CLUSTER_NAME }} -g ${{ secrets.AZURE_RG }} --network-plugin azure --enable-managed-identity -a ingress-appgw --appgw-name ${{ secrets.AAG_INGRESSCONTROLLER }} --appgw-subnet-cidr "10.2.0.0/16" --generate-ssh-keys --attach-acr ${{ secrets.ACR_NAME }} --yes
          az aks nodepool update --enable-cluster-autoscaler --min-count 3 --max-count 10 -g ${{ secrets.AZURE_RG }} -n nodepool1 --cluster-name ${{ secrets.CLUSTER_NAME }}
