on: workflow_dispatch
name: Deploy AKS with Ingress Controller
jobs:
  deploy-cluster:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@main

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy AKS with Ingress Controller
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az aks create ${{ secrets.CLUSTER_NAME }} -g ${{ secrets.AZURE_RG }} --network-plugin azure --enable-managed-identity -a ingress-appgw --appgw-name ${{ secrets.AAG_INGRESSCONTROLLER }} --appgw-subnet-cidr "10.2.0.0/16" --generate-ssh-keys --yes