on: workflow_dispatch
name: Deploy AKS with Ingress Controller
jobs:
  deploy-cluster:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@main

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_SUPER_SP }}
    
    - name: Deploy AKS with Ingress Controller
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az aks create -n ${{ secrets.CLUSTER_NAME }} -g ${{ secrets.AZURE_RG }} --network-plugin azure --enable-managed-identity -a ingress-appgw --appgw-name ${{ secrets.AAG_INGRESSCONTROLLER }} --appgw-subnet-cidr "10.2.0.0/16" --generate-ssh-keys --attach-acr ${{ secrets.ACR_NAME }} --yes
          az aks nodepool update --enable-cluster-autoscaler --min-count 3 --max-count 6 -g ${{ secrets.AZURE_RG }} -n nodepool1 --cluster-name ${{ secrets.CLUSTER_NAME }}
          az resource create --resource-type Microsoft.OperationalInsights/workspaces --name ${{ secrets.WORKSPACE_NAME }} --resource-group ${{ secrets.AZURE_RG }} --location ${{ secrets.REGION_NAME }} --properties '{}' -o table
          WORKSPACE_ID=$(az resource show --resource-type Microsoft.OperationalInsights/workspaces --resource-group ${{ secrets.AZURE_RG }} --name ${{ secrets.WORKSPACE_NAME }} --query "id" -o tsv)
          echo $WORKSPACE_ID
          az aks enable-addons --resource-group ${{ secrets.AZURE_RG }} --name ${{ secrets.CLUSTER_NAME }} --addons monitoring --workspace-resource-id $WORKSPACE_ID
