name: Orchestrator Workflow (Deploy AKS)

on: workflow_dispatch


jobs:
  # ------- Main Orchestration  ---------------
  
  IaC:
    uses: ./.github/workflows/deploy-aks-v2.yml
    with:
      templateLocation: ./IaC/azuredeploy.json
      parametersLocation: ./IaC/azuredeploy.parameters.json
    secrets: 
      rgName: ${{ secrets.AZURE_RG }}
      azureCredentials: ${{ secrets.AZURE_CREDENTIALS_SUPER_SP }}
      azureSubs: ${{ secrets.AZURE_SUBSCRIPTION }}
  
  test-aks:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: IaC
    steps:
      - name: Test AKS
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Test AKS'
  
          
  # ------ Main Orchestration End ---------
  
  # ------- Issue Orchestration ----------
  
  create-issue-aks-iac:
    if: ${{ failure() }}
    needs: [test-aks]
    runs-on: ubuntu-latest
    steps:
      - name: Fail AKS Provisioning
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Fail AKS Provisioning'
                    
   # ------- Issue Orchestration End ----------
