name: Orchestrator Workflow (Deploy AKS)

on: workflow_dispatch


jobs:
  # ------- Main Orchestration  ---------------
  
  deploy-aks:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy AKS (IaC)
        uses: ./.github/workflows/deploy-aks.yml
  
  test-aks:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: deploy-aks
    steps:
      - name: Test AKS
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Test AKS'
  
          
  # ------ Main Orchestration End ---------
  
  # ------- Issue Orchestration ----------
  
  create-issue-aks-iac:
    if: ${{ failure() }}
    needs: [test-aks]
    runs-on: ubuntu-latest
    steps:
      - name: Fail AKS Provisioning
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Fail AKS Provisioning'
                    
   # ------- Issue Orchestration End ----------
