on: workflow_dispatch
name: Udpate AKS with ACR
jobs:
  updating-aks:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@main

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Update AKS with ACR
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az aks get-credentials --name ${{ secrets.CLUSTER_NAME }} --resource-group ${{ secrets.AZURE_RG }}
          az aks update -g ${{ secrets.CLUSTER_AZURE_RG }} -n ${{ secrets.CLUSTER_NAME }} --attach-acr ${{ secrets.ACR_REGISTRY}}
